### ISSUE TITLE
Node worker needs to deal with ffmpeg/rsync failures

### ISSUE THREAD

**Issue by TheSamsai** [TheSamsai/distributed-video-transcoder#1]
If an rsync or ffmpeg command fails, worker should not push results back to job server

**Comment by JoonaHa** [comment]
Commit 0c8ee61 Includes panic when ffmpeg output-file is not found. And a way to pass error info about rsync- and ffmep-childprocesses.

Child-process stdout and sdterr isn't captured correctly and always shows empty. Needs investigating.

**Comment by JoonaHa** [comment]
See commit: 37e097c
